boxcutter/ubuntu

script/vagrant.sh

The create user portion of the script doesn't usually run in the
current implementation because the user is provisioned as part of the
deployment of the base Ubuntu image; nonetheless, the script is
broken as-is.

Don't squash the password if provided

---

script/vmtool.sh

The ISO will end up in the home directory of the SSH user (unless
`tools_upload_path` is explicitly set, which it isn't here); since
this user name is an input, we shouldn't assume that it is "vagrant".
This was fixed as a side effect of #8, but broken again when that was
reverted in commit 0a7b1475.

Use correct path in vmtools

---

script/vagrant.sh

Using best practise for sudoers files.
We need this change to puppet-manage ```/etc/sudoders``` without letting puppet know about vagrant.

Using sudoers.d/vagrant instead of direct sudoers file

---

script/desktop.sh
script/locale.sh
tpl/vagrantfile-ubuntu1604-desktop.tpl
ubuntu1604-desktop.json
ubuntu1604.json

Adds a `desktop` build for Ubuntu 16.04. It uses the same setup as the other desktop builds

Add desktop build for 16.04

---

script/cleanup.sh

If the /var/log folder for example contains a file called '*.log' the cleanup.sh fails with the following bash error: ```ambiguous redirect```.

Fix clean up for log files containing special character

---

script/vagrant.sh

If you choose to build with a specific `SSH_USERNAME`, you mostly don't
want to have explicit vagrant-related stuff in your box

Remove `vagrant` in file names

---

ubuntu1610-i386.json
ubuntu1610.json

_amd64_ tested on:
- Parallels Desktop 12 for Mac Pro Ed. 12.0.2
- VMware Fusion 7.1.3
- VirtualBox 5.1.6

Added Ubuntu 16.10

---

.gitignore
README.md
ubuntu.json

Use of the existing `custom_script` variable to point to a user defined path for more flexibility.
By default, if not changed, the variable points to the existing `custom_script.sh` of root dir, so default behavior is unchanged.

Add flexible custom script support

---

bin/ssh-box

Using mktemp means the name isn't hardcoded, so we can run more than one
box at the same time.  It also guarantees the directory doesn't already
exist.  The bash trap function cleans up the directory even if the
script exits early.
The double mktemp accounts for differences between Mac and Linux mktemp commands.

Better temp directory handling

---

ubuntu.json

I don't know if this setting is appropriate for everyone.  On my Mac, without this setting, the network would inexplicably freeze at certain points in the process, sometimes for up to 10 minutes.  With this setting, that never happens, and boxes build much faster.
I can make this an option if you prefer.

Use virtio for much better network performance

---

script/cleanup.sh

Ubuntu boxes have a number of filesystems.  Shouldn't they all be zero'd, except for the vagrant shared disk?
```
Filesystem                    Size  Used Avail Use% Mounted on
udev                          2.0G     0  2.0G   0% /dev
tmpfs                         396M  5.6M  390M   2% /run
/dev/mapper/vagrant--vg-root   35G  1.2G   32G   4% /
tmpfs                         2.0G     0  2.0G   0% /dev/shm
tmpfs                         5.0M     0  5.0M   0% /run/lock
tmpfs                         2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/sda1                     472M   56M  393M  13% /boot
vagrant                       233G  216G   17G  93% /vagrant
tmpfs                         396M     0  396M   0% /run/user/1000
```
This helps solve https://github.com/boxcutter/ubuntu/issues/91
Also, …

Zero all the filesystems

---

script/minimize.sh

The old command only removed one aspect of the old kernels.  This finds the other packages and also removes them.  This helps solve https://github.com/boxcutter/ubuntu/issues/91

Clean out all of the old kernel packages

---

ubuntu1610-i386.json

in the actual ubuntu i386 json file the machine type is missing. Because of the default values in the inheriting ubuntu.json "Ubuntu 64" is used as machine type. 
Older i386 ubuntu json files did have the machine type set.

missing machine types

---

README.md
bin/register_atlas.sh
ubuntu1604-desktop.json
ubuntu1604.json

In order to build new Ubuntu 16.04 Vagrant Boxes I had to upgrade all .json files to support Ubuntu 16.04.3. This is done for server and desktop versions.
Signed-off-by: Dieter Reuter dieter.reuter@me.com

Upgrade to Ubuntu 16.04.3

---

ubuntu.json

Otherwise update.sh will fail because the reboot disconnects and then packer bails out (see https://github.com/hashicorp/packer/blob/master/CHANGELOG.md#backwards-incompatibilities).

Add support for Packer 1.1: set expect_disconnect to true.

---

ubuntu.json

The vm_name generally gets overridden by the var file, but since the default .iso being used is 16.04, the default vm_name should probably be 1604

default vm_name to ubuntu1604, 16.04 = default iso

---

ubuntu1804.json

Ubunut 18.04 ISOs have already been removed, this updates to the new ISO location with Ubuntu 18.04.1

Update to Ubuntu 18.04.1

---

ubuntu1804.json

I think someone forget to update iso_name according to iso_url variable

update iso_name according to iso_url - ubuntu 18.04

---

ubuntu.json

These two issues were preventing boxes built from this template from being provisioned with Chef due to manual intervention required to fix misconfigured packages. Fixes #141, Fixes #148.

Fix package config issues with ubuntu1604-desktop build

---

script/cleanup.sh

All the project's preeseed files use the "atomic" partitioning scheme,
which puts all files (except boot) on a single partition. Therefore,
/tmp is the same as / and wiping both adds unecessary build time.

Remove redundant wipe of free space on root partition

---

script/desktop.sh

Noticed that autologin wasn't working for Ubuntu 18.04. Turned out in my last PR I made a typo. This fixes it.

Fix typo that disabled autologin for Ubuntu 18.04

---

ubuntu1404.json

Current checksum for ubuntu1404 is wrong, so you cannot build images.  
Also, the iso file is a little bit old.
This PR will update them so that you can build ubuntu1404 image, with the latest iso file.

Update iso_url for ubuntu1404

---

script/cleanup.sh

By default, the machine-id is used as the DUID to identify the machine to a DHCP server. If two machines have the same machine-id, they are assigned the same IP-Address.
Same bug in chef/bento: [#1062](https://github.com/chef/bento/issues/1062)
Relevant systemd documentation: [ machine-id(5)](https://www.freedesktop.org/software/systemd/man/machine-id.html#Initialization)

Blank /etc/machine-id so machines generate a new ID on first boot
